
package SistemaVendas.view;

import SistemaVendas.beans.Cliente;
import SistemaVendas.beans.NotaSaida;
import SistemaVendas.beans.Produto;
import SistemasVendas.dao.ClienteDAO;
import SistemasVendas.dao.NotaSaidaDAO;
import SistemasVendas.dao.ProdutoDAO;
import java.util.List;
import javax.swing.JOptionPane;

/**
 *
 * @author clara
 */
public class TelaLancamentoNota extends javax.swing.JFrame {

    private void popularComboBoxes() {
    // Popula a lista de clientes
    ClienteDAO clienteDAO = new ClienteDAO();
    List<Cliente> listaClientes = clienteDAO.getClientes();
    for (Cliente cliente : listaClientes) {
        comboCliente.addItem(cliente); 
    }

    // Popula a lista de produtos
    ProdutoDAO produtoDAO = new ProdutoDAO();
    List<Produto> listaProdutos = produtoDAO.getProdutos();
    for (Produto produto : listaProdutos) {
        comboProduto.addItem(produto); // O toString() do Produto será exibido
    }
}
    
    
    public TelaLancamentoNota() {
        initComponents();
        popularComboBoxes();
    }

    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        comboCliente = new javax.swing.JComboBox<>();
        comboProduto = new javax.swing.JComboBox<>();
        txtQuantidade = new javax.swing.JTextField();
        btnLimparVenda = new javax.swing.JButton();
        btnSalvarVenda = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Cliente");

        jLabel2.setText("Produto");

        jLabel3.setText("Quantidade Vendida");

        txtQuantidade.setText("jTextField1");

        btnLimparVenda.setText("Limpar");
        btnLimparVenda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLimparVendaActionPerformed(evt);
            }
        });

        btnSalvarVenda.setText("Salvar Venda");
        btnSalvarVenda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalvarVendaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(jLabel1)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(comboCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createSequentialGroup()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel2)
                                .addComponent(jLabel3))
                            .addGap(66, 66, 66)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(comboProduto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(txtQuantidade, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnLimparVenda)
                        .addGap(84, 84, 84)
                        .addComponent(btnSalvarVenda)))
                .addContainerGap(148, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(comboCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(21, 21, 21)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(comboProduto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtQuantidade, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnLimparVenda)
                    .addComponent(btnSalvarVenda))
                .addContainerGap(139, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnLimparVendaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLimparVendaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnLimparVendaActionPerformed

    private void btnSalvarVendaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalvarVendaActionPerformed
                                               
    try {
        // 1. Pegar os objetos selecionados nas listas
        Cliente clienteSelecionado = (Cliente) comboCliente.getSelectedItem();
        Produto produtoSelecionado = (Produto) comboProduto.getSelectedItem();

        // 2. Pegar a quantidade e converter para número
        int quantidadeVendida = Integer.parseInt(txtQuantidade.getText());

        // 3. VALIDAR O ESTOQUE
        if (produtoSelecionado.getQuantidadeEstoque() < quantidadeVendida) {
            JOptionPane.showMessageDialog(this, "Erro: Estoque insuficiente! Estoque atual: " + produtoSelecionado.getQuantidadeEstoque());
            return; // Interrompe a operação de salvar
        }

        // 4. Se o estoque estiver OK, cria o objeto NotaSaida
        NotaSaida nota = new NotaSaida();
        nota.setIdCliente(clienteSelecionado.getId());
        nota.setIdProduto(produtoSelecionado.getId());
        nota.setQuantidadeVendida(quantidadeVendida);
        nota.setDataVenda(new java.sql.Date(System.currentTimeMillis())); 

        // 5. Salva no banco de dados através do DAO
        NotaSaidaDAO notaDAO = new NotaSaidaDAO();
        notaDAO.inserir(nota);

        // 6. Mensagem de sucesso e limpeza
        JOptionPane.showMessageDialog(this, "Venda registrada com sucesso!");
        // Limpar campos...

    } catch (NumberFormatException e) {
        JOptionPane.showMessageDialog(this, "Erro: A quantidade deve ser um número válido.");
    } catch (Exception e) {
        JOptionPane.showMessageDialog(this, "Ocorreu um erro: " + e.getMessage());
    }

    }//GEN-LAST:event_btnSalvarVendaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaLancamentoNota.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaLancamentoNota.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaLancamentoNota.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaLancamentoNota.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaLancamentoNota().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnLimparVenda;
    private javax.swing.JButton btnSalvarVenda;
    private javax.swing.JComboBox<Cliente> comboCliente;
    private javax.swing.JComboBox<Produto> comboProduto;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JTextField txtQuantidade;
    // End of variables declaration//GEN-END:variables
}
